# docker-compose.yml
version: "3.9"

services:
  db:
    build:
      context: .
      dockerfile: postgres.Dockerfile
    container_name: sparkle_universe
    restart: unless-stopped
    environment:
      POSTGRES_USER: sparkle_user
      POSTGRES_PASSWORD: StrongPass1234
      POSTGRES_DB: sparkle_db
    ports:
      - "5433:5432"  # Corrected: Maps host port 5433 to container port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
    driver: local
